name: Deploy to EKS
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configure AWS credentials (using secrets)
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      # 4. Build and push Docker image
      - name: Build and Push
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/url-shortener:latest .
          docker push ${{ secrets.ECR_REGISTRY }}/url-shortener:latest

      # 5. Deploy to EKS
      - name: Deploy to Kubernetes
        run: |
          aws eks update-kubeconfig --name url-shortener-eks --region ${{ secrets.AWS_REGION }}
          kubectl apply -f k8s/
